"""add document chunks

Revision ID: 38289d6e6f86
Revises: 1a7642072efd
Create Date: 2026-06-07 01:44:15.575199

"""
from typing import Sequence, Union

from alembic import op
import pgvector.sqlalchemy
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '38289d6e6f86'
down_revision: Union[str, Sequence[str], None] = '1a7642072efd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    op.create_table('document_chunks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('owner_type', sa.Enum('job', 'application', name='document_owner_type'), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('source', sa.Enum('jd', 'cv', name='document_chunk_source'), nullable=False),
    sa.Column('section', sa.String(), nullable=True),
    sa.Column('chunk_text', sa.Text(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=2048), nullable=False),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_chunks_owner_id'), 'document_chunks', ['owner_id'], unique=False)
    op.create_index(op.f('ix_document_chunks_owner_type'), 'document_chunks', ['owner_type'], unique=False)
    op.create_index(op.f('ix_document_chunks_source'), 'document_chunks', ['source'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_document_chunks_source'), table_name='document_chunks')
    op.drop_index(op.f('ix_document_chunks_owner_type'), table_name='document_chunks')
    op.drop_index(op.f('ix_document_chunks_owner_id'), table_name='document_chunks')
    op.drop_table('document_chunks')
    op.execute("DROP TYPE IF EXISTS document_chunk_source")
    op.execute("DROP TYPE IF EXISTS document_owner_type")
    # ### end Alembic commands ###
