"""update time for events

Revision ID: 7800f4720140
Revises: 78ce9df1fc75
Create Date: 2026-06-17 23:41:44.704921

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7800f4720140'
down_revision: Union[str, Sequence[str], None] = '78ce9df1fc75'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('applications', sa.Column('test_score', sa.Float(), nullable=True))
    op.drop_column('applications', 'total_score')
    op.add_column('jobs', sa.Column('cv_submission_deadline', sa.DateTime(), nullable=True))
    op.add_column('jobs', sa.Column('test_start_date', sa.DateTime(), nullable=True))
    op.add_column('jobs', sa.Column('test_end_date', sa.DateTime(), nullable=True))
    op.add_column('jobs', sa.Column('interview_start_date', sa.DateTime(), nullable=True))
    op.add_column('jobs', sa.Column('interview_end_date', sa.DateTime(), nullable=True))
    op.add_column('jobs', sa.Column('result_announcement_date', sa.DateTime(), nullable=True))
    op.drop_column('jobs', 'test_duration')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('test_duration', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('jobs', 'result_announcement_date')
    op.drop_column('jobs', 'interview_end_date')
    op.drop_column('jobs', 'interview_start_date')
    op.drop_column('jobs', 'test_end_date')
    op.drop_column('jobs', 'test_start_date')
    op.drop_column('jobs', 'cv_submission_deadline')
    op.add_column('applications', sa.Column('total_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_column('applications', 'test_score')
    # ### end Alembic commands ###
