"""add_hiring_quotas

Revision ID: 78ce9df1fc75
Revises: b583935db2d8
Create Date: 2026-06-13 21:53:11.566502

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '78ce9df1fc75'
down_revision: Union[str, Sequence[str], None] = 'b583935db2d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('cv_pass_quota', sa.Integer(), nullable=True))
    op.add_column('jobs', sa.Column('assessment_pass_quota', sa.Integer(), nullable=True))
    op.add_column('jobs', sa.Column('interview_pass_quota', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'interview_pass_quota')
    op.drop_column('jobs', 'assessment_pass_quota')
    op.drop_column('jobs', 'cv_pass_quota')
    # ### end Alembic commands ###
