"""update job attributes

Revision ID: b583935db2d8
Revises: 6be302d65b1a
Create Date: 2026-06-13 00:38:17.546856

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b583935db2d8'
down_revision: Union[str, Sequence[str], None] = '6be302d65b1a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('dynamic_test_config', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('jobs', sa.Column('test_duration', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'test_duration')
    op.drop_column('jobs', 'dynamic_test_config')
    # ### end Alembic commands ###
